version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api:dev
    environment:
      REPLYEMAIL: REPLYEMAIL
      MAILGUNEMAIL: MAILGUNEMAIL
      MAILGUNDOMAIN: MAILGUNDOMAIN
      MAILGUN_API_KEY: MAILGUN_API_KEY
      SENDGRIDEMAIL: SENDGRIDEMAIL
      SENDGRID_API_KEY: SENDGRID_API_KEY
      USERNAME: postgres
      PASSWORD: postgres
      DATABASE: postgres
      HOSTNAME: db
      TLS: false
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres