import Vapor
import RoutingKit

// routes.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: 

extension String {
  var asPathComponents: [PathComponent] {
    return self.split(separator: "/").map {
      if $0.starts(with: "{") && $0.hasSuffix("}") {
        let start = $0.index($0.startIndex, offsetBy: 1)
        let end = $0.index($0.endIndex, offsetBy: -1)
        return PathComponent.parameter(String($0[start..<end]))
      } else {
        return PathComponent.constant(.init($0))
      }
    }
  }
}

public protocol AuthenticationMiddleware: Middleware {
  associatedtype AuthType: Authenticatable
  func authType() -> AuthType.Type
}

//Used when auth is not used
public class DummyAuthType: Authenticatable {}

public func routes<authForBearer: AuthenticationMiddleware, backend: BackendApiDelegate>
  (_ app: RoutesBuilder, backend: backend, authForBearer: authForBearer)
  throws
  where authForBearer.AuthType == backend.AuthType
  {
  let groupForBearer = app.grouped([authForBearer])
  //for admin
  groupForBearer.on(.DELETE, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatDeleteResponse> in
    let chatEntryDTOIdOptional = try? request.query.get(UUID.self, at: "chatEntryDTOId")
    guard let chatEntryDTOId = chatEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatEntryDTOId")
    }
    return try backend.chatDelete(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatEntryDTOId: chatEntryDTOId)
  }
  groupForBearer.on(.GET, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatGetResponse> in
    return try backend.chatGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.PATCH, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatPatchResponse> in
    let chatEntryDTOIdOptional = try? request.query.get(UUID.self, at: "chatEntryDTOId")
    guard let chatEntryDTOId = chatEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatEntryDTOId")
    }
    return try backend.chatPatch(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatEntryDTOId: chatEntryDTOId)
  }
  groupForBearer.on(.POST, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatPostResponse> in
    let chatIdOptional = try? request.query.get(UUID.self, at: "chatId")
    guard let chatId = chatIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatId")
    }
    let messageOptional = try? request.query.get(String.self, at: "message")
    guard let message = messageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter message")
    }
    return try backend.chatPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatId: chatId, message: message)
  }
  groupForBearer.on(.PUT, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatPutResponse> in
    let chatEntryDTOIdOptional = try? request.query.get(UUID.self, at: "chatEntryDTOId")
    guard let chatEntryDTOId = chatEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatEntryDTOId")
    }
    let modifiedMessageOptional = try? request.query.get(String.self, at: "modifiedMessage")
    guard let modifiedMessage = modifiedMessageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter modifiedMessage")
    }
    return try backend.chatPut(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatEntryDTOId: chatEntryDTOId, modifiedMessage: modifiedMessage)
  }
  groupForBearer.on(.DELETE, "/exercise".asPathComponents) { (request: Request) -> EventLoopFuture<exerciseDeleteResponse> in
    let exerciseIdOptional = try? request.query.get(UUID.self, at: "exerciseId")
    guard let exerciseId = exerciseIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter exerciseId")
    }
    return try backend.exerciseDelete(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), exerciseId: exerciseId)
  }
  groupForBearer.on(.GET, "/exercise".asPathComponents) { (request: Request) -> EventLoopFuture<exerciseGetResponse> in
    return try backend.exerciseGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.POST, "/exercise".asPathComponents) { (request: Request) -> EventLoopFuture<exercisePostResponse> in
    let body = try request.content.decode(ExerciseDTO.self)
    return try backend.exercisePost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), body: body)
  }
  groupForBearer.on(.PUT, "/exercise".asPathComponents) { (request: Request) -> EventLoopFuture<exercisePutResponse> in
    let body = try request.content.decode(ExerciseDTO.self)
    return try backend.exercisePut(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), body: body)
  }
  app.on(.POST, "/forgotPassword".asPathComponents) { (request: Request) -> EventLoopFuture<forgotPasswordPostResponse> in
    let emailOptional = try? request.query.get(String.self, at: "email")
    guard let email = emailOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter email")
    }
    return try backend.forgotPasswordPost(with: request, email: email)
  }
  groupForBearer.on(.DELETE, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupDeleteResponse> in
    let groupEntryDTOIdOptional = try? request.query.get(UUID.self, at: "groupEntryDTOId")
    guard let groupEntryDTOId = groupEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupEntryDTOId")
    }
    return try backend.groupDelete(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupEntryDTOId: groupEntryDTOId)
  }
  groupForBearer.on(.GET, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupGetResponse> in
    return try backend.groupGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.DELETE, "/groupManaging".asPathComponents) { (request: Request) -> EventLoopFuture<groupManagingDeleteResponse> in
    let body = try request.content.decode(String.self)
    return try backend.groupManagingDelete(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), body: body)
  }
  groupForBearer.on(.GET, "/groupManaging".asPathComponents) { (request: Request) -> EventLoopFuture<groupManagingGetResponse> in
    return try backend.groupManagingGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.POST, "/groupManaging".asPathComponents) { (request: Request) -> EventLoopFuture<groupManagingPostResponse> in
    let body = try request.content.decode(String.self)
    return try backend.groupManagingPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), body: body)
  }
  groupForBearer.on(.PATCH, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupPatchResponse> in
    let groupEntryDTOIdOptional = try? request.query.get(UUID.self, at: "groupEntryDTOId")
    guard let groupEntryDTOId = groupEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupEntryDTOId")
    }
    return try backend.groupPatch(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupEntryDTOId: groupEntryDTOId)
  }
  groupForBearer.on(.POST, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupPostResponse> in
    let groupIdOptional = try? request.query.get(UUID.self, at: "groupId")
    guard let groupId = groupIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupId")
    }
    let messageOptional = try? request.query.get(String.self, at: "message")
    guard let message = messageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter message")
    }
    return try backend.groupPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupId: groupId, message: message)
  }
  groupForBearer.on(.PUT, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupPutResponse> in
    let groupEntryDTOIdOptional = try? request.query.get(UUID.self, at: "groupEntryDTOId")
    guard let groupEntryDTOId = groupEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupEntryDTOId")
    }
    let modifiedMessageOptional = try? request.query.get(UUID.self, at: "modifiedMessage")
    guard let modifiedMessage = modifiedMessageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter modifiedMessage")
    }
    return try backend.groupPut(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupEntryDTOId: groupEntryDTOId, modifiedMessage: modifiedMessage)
  }
  app.on(.POST, "/login".asPathComponents) { (request: Request) -> EventLoopFuture<loginPostResponse> in
    let emailOptional = try? request.query.get(String.self, at: "email")
    guard let email = emailOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter email")
    }
    let passwordOptional = try? request.query.get(String.self, at: "password")
    guard let password = passwordOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter password")
    }
    return try backend.loginPost(with: request, email: email, password: password)
  }
  groupForBearer.on(.POST, "/logout".asPathComponents) { (request: Request) -> EventLoopFuture<logoutPostResponse> in
    return try backend.logoutPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.POST, "/searchUser".asPathComponents) { (request: Request) -> EventLoopFuture<searchUserPostResponse> in
    let nameOptional = try? request.query.get(String.self, at: "name")
    guard let name = nameOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter name")
    }
    return try backend.searchUserPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), name: name)
  }
  app.on(.GET, "/test".asPathComponents) { (request: Request) -> EventLoopFuture<testGetResponse> in
    return try backend.testGet(with: request)
  }
  //for backend
  groupForBearer.on(.DELETE, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatDeleteResponse> in
    let chatEntryDTOIdOptional = try? request.query.get(UUID.self, at: "chatEntryDTOId")
    guard let chatEntryDTOId = chatEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatEntryDTOId")
    }
    return try backend.chatDelete(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatEntryDTOId: chatEntryDTOId)
  }
  groupForBearer.on(.GET, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatGetResponse> in
    return try backend.chatGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.PATCH, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatPatchResponse> in
    let chatEntryDTOIdOptional = try? request.query.get(UUID.self, at: "chatEntryDTOId")
    guard let chatEntryDTOId = chatEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatEntryDTOId")
    }
    return try backend.chatPatch(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatEntryDTOId: chatEntryDTOId)
  }
  groupForBearer.on(.POST, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatPostResponse> in
    let chatIdOptional = try? request.query.get(UUID.self, at: "chatId")
    guard let chatId = chatIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatId")
    }
    let messageOptional = try? request.query.get(String.self, at: "message")
    guard let message = messageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter message")
    }
    return try backend.chatPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatId: chatId, message: message)
  }
  groupForBearer.on(.PUT, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatPutResponse> in
    let chatEntryDTOIdOptional = try? request.query.get(UUID.self, at: "chatEntryDTOId")
    guard let chatEntryDTOId = chatEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatEntryDTOId")
    }
    let modifiedMessageOptional = try? request.query.get(String.self, at: "modifiedMessage")
    guard let modifiedMessage = modifiedMessageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter modifiedMessage")
    }
    return try backend.chatPut(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatEntryDTOId: chatEntryDTOId, modifiedMessage: modifiedMessage)
  }
  groupForBearer.on(.DELETE, "/exercise".asPathComponents) { (request: Request) -> EventLoopFuture<exerciseDeleteResponse> in
    let exerciseIdOptional = try? request.query.get(UUID.self, at: "exerciseId")
    guard let exerciseId = exerciseIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter exerciseId")
    }
    return try backend.exerciseDelete(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), exerciseId: exerciseId)
  }
  groupForBearer.on(.GET, "/exercise".asPathComponents) { (request: Request) -> EventLoopFuture<exerciseGetResponse> in
    return try backend.exerciseGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.POST, "/exercise".asPathComponents) { (request: Request) -> EventLoopFuture<exercisePostResponse> in
    let body = try request.content.decode(ExerciseDTO.self)
    return try backend.exercisePost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), body: body)
  }
  groupForBearer.on(.PUT, "/exercise".asPathComponents) { (request: Request) -> EventLoopFuture<exercisePutResponse> in
    let body = try request.content.decode(ExerciseDTO.self)
    return try backend.exercisePut(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), body: body)
  }
  app.on(.POST, "/forgotPassword".asPathComponents) { (request: Request) -> EventLoopFuture<forgotPasswordPostResponse> in
    let emailOptional = try? request.query.get(String.self, at: "email")
    guard let email = emailOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter email")
    }
    return try backend.forgotPasswordPost(with: request, email: email)
  }
  groupForBearer.on(.DELETE, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupDeleteResponse> in
    let groupEntryDTOIdOptional = try? request.query.get(UUID.self, at: "groupEntryDTOId")
    guard let groupEntryDTOId = groupEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupEntryDTOId")
    }
    return try backend.groupDelete(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupEntryDTOId: groupEntryDTOId)
  }
  groupForBearer.on(.GET, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupGetResponse> in
    return try backend.groupGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.DELETE, "/groupManaging".asPathComponents) { (request: Request) -> EventLoopFuture<groupManagingDeleteResponse> in
    let body = try request.content.decode(String.self)
    return try backend.groupManagingDelete(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), body: body)
  }
  groupForBearer.on(.GET, "/groupManaging".asPathComponents) { (request: Request) -> EventLoopFuture<groupManagingGetResponse> in
    return try backend.groupManagingGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.POST, "/groupManaging".asPathComponents) { (request: Request) -> EventLoopFuture<groupManagingPostResponse> in
    let body = try request.content.decode(String.self)
    return try backend.groupManagingPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), body: body)
  }
  groupForBearer.on(.PATCH, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupPatchResponse> in
    let groupEntryDTOIdOptional = try? request.query.get(UUID.self, at: "groupEntryDTOId")
    guard let groupEntryDTOId = groupEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupEntryDTOId")
    }
    return try backend.groupPatch(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupEntryDTOId: groupEntryDTOId)
  }
  groupForBearer.on(.POST, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupPostResponse> in
    let groupIdOptional = try? request.query.get(UUID.self, at: "groupId")
    guard let groupId = groupIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupId")
    }
    let messageOptional = try? request.query.get(String.self, at: "message")
    guard let message = messageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter message")
    }
    return try backend.groupPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupId: groupId, message: message)
  }
  groupForBearer.on(.PUT, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupPutResponse> in
    let groupEntryDTOIdOptional = try? request.query.get(UUID.self, at: "groupEntryDTOId")
    guard let groupEntryDTOId = groupEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupEntryDTOId")
    }
    let modifiedMessageOptional = try? request.query.get(UUID.self, at: "modifiedMessage")
    guard let modifiedMessage = modifiedMessageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter modifiedMessage")
    }
    return try backend.groupPut(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupEntryDTOId: groupEntryDTOId, modifiedMessage: modifiedMessage)
  }
  app.on(.POST, "/login".asPathComponents) { (request: Request) -> EventLoopFuture<loginPostResponse> in
    let emailOptional = try? request.query.get(String.self, at: "email")
    guard let email = emailOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter email")
    }
    let passwordOptional = try? request.query.get(String.self, at: "password")
    guard let password = passwordOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter password")
    }
    return try backend.loginPost(with: request, email: email, password: password)
  }
  groupForBearer.on(.POST, "/logout".asPathComponents) { (request: Request) -> EventLoopFuture<logoutPostResponse> in
    return try backend.logoutPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  app.on(.POST, "/register".asPathComponents) { (request: Request) -> EventLoopFuture<registerPostResponse> in
    let nameOptional = try? request.query.get(String.self, at: "name")
    guard let name = nameOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter name")
    }
    let emailOptional = try? request.query.get(String.self, at: "email")
    guard let email = emailOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter email")
    }
    let passwordOptional = try? request.query.get(String.self, at: "password")
    guard let password = passwordOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter password")
    }
    return try backend.registerPost(with: request, name: name, email: email, password: password)
  }
  groupForBearer.on(.POST, "/searchUser".asPathComponents) { (request: Request) -> EventLoopFuture<searchUserPostResponse> in
    let nameOptional = try? request.query.get(String.self, at: "name")
    guard let name = nameOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter name")
    }
    return try backend.searchUserPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), name: name)
  }
  app.on(.GET, "/test".asPathComponents) { (request: Request) -> EventLoopFuture<testGetResponse> in
    return try backend.testGet(with: request)
  }
  //for client
  groupForBearer.on(.DELETE, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatDeleteResponse> in
    let chatEntryDTOIdOptional = try? request.query.get(UUID.self, at: "chatEntryDTOId")
    guard let chatEntryDTOId = chatEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatEntryDTOId")
    }
    return try backend.chatDelete(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatEntryDTOId: chatEntryDTOId)
  }
  groupForBearer.on(.GET, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatGetResponse> in
    return try backend.chatGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.PATCH, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatPatchResponse> in
    let chatEntryDTOIdOptional = try? request.query.get(UUID.self, at: "chatEntryDTOId")
    guard let chatEntryDTOId = chatEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatEntryDTOId")
    }
    return try backend.chatPatch(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatEntryDTOId: chatEntryDTOId)
  }
  groupForBearer.on(.POST, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatPostResponse> in
    let chatIdOptional = try? request.query.get(UUID.self, at: "chatId")
    guard let chatId = chatIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatId")
    }
    let messageOptional = try? request.query.get(String.self, at: "message")
    guard let message = messageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter message")
    }
    return try backend.chatPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatId: chatId, message: message)
  }
  groupForBearer.on(.PUT, "/chat".asPathComponents) { (request: Request) -> EventLoopFuture<chatPutResponse> in
    let chatEntryDTOIdOptional = try? request.query.get(UUID.self, at: "chatEntryDTOId")
    guard let chatEntryDTOId = chatEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter chatEntryDTOId")
    }
    let modifiedMessageOptional = try? request.query.get(String.self, at: "modifiedMessage")
    guard let modifiedMessage = modifiedMessageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter modifiedMessage")
    }
    return try backend.chatPut(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), chatEntryDTOId: chatEntryDTOId, modifiedMessage: modifiedMessage)
  }
  groupForBearer.on(.GET, "/exercise".asPathComponents) { (request: Request) -> EventLoopFuture<exerciseGetResponse> in
    return try backend.exerciseGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  app.on(.POST, "/forgotPassword".asPathComponents) { (request: Request) -> EventLoopFuture<forgotPasswordPostResponse> in
    let emailOptional = try? request.query.get(String.self, at: "email")
    guard let email = emailOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter email")
    }
    return try backend.forgotPasswordPost(with: request, email: email)
  }
  groupForBearer.on(.DELETE, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupDeleteResponse> in
    let groupEntryDTOIdOptional = try? request.query.get(UUID.self, at: "groupEntryDTOId")
    guard let groupEntryDTOId = groupEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupEntryDTOId")
    }
    return try backend.groupDelete(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupEntryDTOId: groupEntryDTOId)
  }
  groupForBearer.on(.GET, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupGetResponse> in
    return try backend.groupGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.DELETE, "/groupManaging".asPathComponents) { (request: Request) -> EventLoopFuture<groupManagingDeleteResponse> in
    let body = try request.content.decode(String.self)
    return try backend.groupManagingDelete(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), body: body)
  }
  groupForBearer.on(.GET, "/groupManaging".asPathComponents) { (request: Request) -> EventLoopFuture<groupManagingGetResponse> in
    return try backend.groupManagingGet(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  groupForBearer.on(.POST, "/groupManaging".asPathComponents) { (request: Request) -> EventLoopFuture<groupManagingPostResponse> in
    let body = try request.content.decode(String.self)
    return try backend.groupManagingPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), body: body)
  }
  groupForBearer.on(.PATCH, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupPatchResponse> in
    let groupEntryDTOIdOptional = try? request.query.get(UUID.self, at: "groupEntryDTOId")
    guard let groupEntryDTOId = groupEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupEntryDTOId")
    }
    return try backend.groupPatch(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupEntryDTOId: groupEntryDTOId)
  }
  groupForBearer.on(.POST, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupPostResponse> in
    let groupIdOptional = try? request.query.get(UUID.self, at: "groupId")
    guard let groupId = groupIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupId")
    }
    let messageOptional = try? request.query.get(String.self, at: "message")
    guard let message = messageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter message")
    }
    return try backend.groupPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupId: groupId, message: message)
  }
  groupForBearer.on(.PUT, "/group".asPathComponents) { (request: Request) -> EventLoopFuture<groupPutResponse> in
    let groupEntryDTOIdOptional = try? request.query.get(UUID.self, at: "groupEntryDTOId")
    guard let groupEntryDTOId = groupEntryDTOIdOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter groupEntryDTOId")
    }
    let modifiedMessageOptional = try? request.query.get(UUID.self, at: "modifiedMessage")
    guard let modifiedMessage = modifiedMessageOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter modifiedMessage")
    }
    return try backend.groupPut(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), groupEntryDTOId: groupEntryDTOId, modifiedMessage: modifiedMessage)
  }
  app.on(.POST, "/login".asPathComponents) { (request: Request) -> EventLoopFuture<loginPostResponse> in
    let emailOptional = try? request.query.get(String.self, at: "email")
    guard let email = emailOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter email")
    }
    let passwordOptional = try? request.query.get(String.self, at: "password")
    guard let password = passwordOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter password")
    }
    return try backend.loginPost(with: request, email: email, password: password)
  }
  groupForBearer.on(.POST, "/logout".asPathComponents) { (request: Request) -> EventLoopFuture<logoutPostResponse> in
    return try backend.logoutPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()))
  }
  app.on(.POST, "/register".asPathComponents) { (request: Request) -> EventLoopFuture<registerPostResponse> in
    let nameOptional = try? request.query.get(String.self, at: "name")
    guard let name = nameOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter name")
    }
    let emailOptional = try? request.query.get(String.self, at: "email")
    guard let email = emailOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter email")
    }
    let passwordOptional = try? request.query.get(String.self, at: "password")
    guard let password = passwordOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter password")
    }
    return try backend.registerPost(with: request, name: name, email: email, password: password)
  }
  groupForBearer.on(.POST, "/searchUser".asPathComponents) { (request: Request) -> EventLoopFuture<searchUserPostResponse> in
    let nameOptional = try? request.query.get(String.self, at: "name")
    guard let name = nameOptional else {
      throw Abort(HTTPResponseStatus.badRequest, reason: "Missing query parameter name")
    }
    return try backend.searchUserPost(with: request, asAuthenticated: request.auth.require(authForBearer.authType()), name: name)
  }
  app.on(.GET, "/test".asPathComponents) { (request: Request) -> EventLoopFuture<testGetResponse> in
    return try backend.testGet(with: request)
  }
}

