//
// CharacteristicsTypeDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.CharacteristicsTypeDTO

import Vapor

public enum CharacteristicsTypeDTO: String, Codable {
    case arms = "arms"
    case legs = "legs"
}