//
// CharacteristicsDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.CharacteristicsDTO

import Vapor


public final class CharacteristicsDTO: Content {

    public var firstHalfPositionType: HalfPositionTypeDTO?
    public var firstFullPositionType: FullPositionTypeDTO?
    public var secondFullPositionType: FullPositionTypeDTO?
    public var secondHalfPositionType: HalfPositionTypeDTO?
    public var distanceType: DistanceTypeDTO?
    public var type: CharacteristicsTypeDTO

    public init(firstHalfPositionType: HalfPositionTypeDTO?, firstFullPositionType: FullPositionTypeDTO?, secondFullPositionType: FullPositionTypeDTO?, secondHalfPositionType: HalfPositionTypeDTO?, distanceType: DistanceTypeDTO?, type: CharacteristicsTypeDTO) { 
        self.firstHalfPositionType = firstHalfPositionType
        self.firstFullPositionType = firstFullPositionType
        self.secondFullPositionType = secondFullPositionType
        self.secondHalfPositionType = secondHalfPositionType
        self.distanceType = distanceType
        self.type = type
    }
}
