//
// ChatDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ChatDTO

import Vapor


public final class ChatDTO: Content {

    public var primaryId: UUID
    public var users: [UUID]
    public var chatEntries: [ChatEntryDTO]

    public init(primaryId: UUID, users: [UUID], chatEntries: [ChatEntryDTO]) { 
        self.primaryId = primaryId
        self.users = users
        self.chatEntries = chatEntries
    }
}
