//
// ChatEntryDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ChatEntryDTO

import Vapor


public final class ChatEntryDTO: Content {

    public var primaryId: UUID
    public var message: String
    /** In epoch seconds */
    public var timestamp: Int
    public var sender: UUID
    public var deleted: Bool

    public init(primaryId: UUID, message: String, timestamp: Int, sender: UUID, deleted: Bool) { 
        self.primaryId = primaryId
        self.message = message
        self.timestamp = timestamp
        self.sender = sender
        self.deleted = deleted
    }
}
