//
// DistanceTypeDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.DistanceTypeDTO

import Vapor

public enum DistanceTypeDTO: String, Codable {
    case around0 = "around0"
    case around1 = "around1"
    case around2 = "around2"
    case around3 = "around3"
    case around4 = "around4"
    case aroundminus1 = "aroundMinus1"
    case aroundminus2 = "aroundMinus2"
    case aroundminus3 = "aroundMinus3"
    case aroundminus4 = "aroundMinus4"
}