//
// ExerciseFractionTimeUnitDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ExerciseFractionTimeUnitDTO

import Vapor


public final class ExerciseFractionTimeUnitDTO: Content {

    /** In milliseconds from the beginning of the video */
    public var fromTime: Int
    /** In milliseconds from the beginning of the video */
    public var toTime: Int

    public init(fromTime: Int, toTime: Int) { 
        self.fromTime = fromTime
        self.toTime = toTime
    }
}
