//
// ExerciseTypeDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ExerciseTypeDTO

import Vapor

public enum ExerciseTypeDTO: String, Codable {
    case running = "running"
    case highjump = "highJump"
    case stretching = "stretching"
}