//
// ExerciseModelDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ExerciseModelDTO

import Vapor


public final class ExerciseModelDTO: Content {

    public var sequence: [ExerciseMomentDTO]
    public var sequenceCount: Int
    public var delay: Double

    public init(sequence: [ExerciseMomentDTO], sequenceCount: Int, delay: Double) { 
        self.sequence = sequence
        self.sequenceCount = sequenceCount
        self.delay = delay
    }
}
