//
// ExerciseErrorDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ExerciseErrorDTO

import Vapor


public final class ExerciseErrorDTO: Content {

    public var `id`: UUID
    public var characteristics: CharacteristicsDTO
    /** the identifier of the client side text */
    public var error: String

    public init(`id`: UUID, characteristics: CharacteristicsDTO, error: String) { 
        self.`id` = `id`
        self.characteristics = characteristics
        self.error = error
    }
}
