//
// ExerciseMomentDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ExerciseMomentDTO

import Vapor


public final class ExerciseMomentDTO: Content {

    public var armCharacteristics: CharacteristicsDTO
    public var legCharacteristics: CharacteristicsDTO
    public var errors: [ExerciseErrorDTO]

    public init(armCharacteristics: CharacteristicsDTO, legCharacteristics: CharacteristicsDTO, errors: [ExerciseErrorDTO]) { 
        self.armCharacteristics = armCharacteristics
        self.legCharacteristics = legCharacteristics
        self.errors = errors
    }
}
