//
// ExerciseErrorDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ExerciseErrorDTO

import Vapor


public final class ExerciseErrorDTO: Content {

    public var characteristics: CharacteristicsDTO
    public var error: String

    public init(characteristics: CharacteristicsDTO, error: String) { 
        self.characteristics = characteristics
        self.error = error
    }
}
