//
// ExerciseModelDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ExerciseModelDTO

import Vapor


public final class ExerciseModelDTO: Content {

    public var `id`: UUID
    public var sequence: [ExerciseMomentDTO]
    public var sequenceCount: Int
    public var delay: Double
    /** the 11 character long id of the YouTube video */
    public var videoId: String

    public init(`id`: UUID, sequence: [ExerciseMomentDTO], sequenceCount: Int, delay: Double, videoId: String) { 
        self.`id` = `id`
        self.sequence = sequence
        self.sequenceCount = sequenceCount
        self.delay = delay
        self.videoId = videoId
    }
}
