//
// ExerciseDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ExerciseDTO

import Vapor


public final class ExerciseDTO: Content {

    public var primaryId: UUID
    public var exerciseType: ExerciseTypeDTO
    public var previewImage: String
    public var exerciseVideoUrl: String
    public var fractions: [ExerciseFractionDTO]

    public init(primaryId: UUID, exerciseType: ExerciseTypeDTO, previewImage: String, exerciseVideoUrl: String, fractions: [ExerciseFractionDTO]) { 
        self.primaryId = primaryId
        self.exerciseType = exerciseType
        self.previewImage = previewImage
        self.exerciseVideoUrl = exerciseVideoUrl
        self.fractions = fractions
    }
}
