//
// ExerciseFractionTimeUnitDurationDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.ExerciseFractionTimeUnitDurationDTO

import Vapor


public final class ExerciseFractionTimeUnitDurationDTO: Content {

    /** In milliseconds from the beginning of the video */
    public var fromTime: Int
    /** In milliseconds from the beginning of the fraction */
    public var duration: Int

    public init(fromTime: Int, duration: Int) { 
        self.fromTime = fromTime
        self.duration = duration
    }
}
