//
// FullPositionTypeDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.FullPositionTypeDTO

import Vapor

public enum FullPositionTypeDTO: String, Codable {
    case around0 = "around0"
    case around45 = "around45"
    case around90 = "around90"
    case around135 = "around135"
    case around180 = "around180"
    case around225 = "around225"
    case around270 = "around270"
    case around315 = "around315"
}