//
// HalfPositionTypeDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.HalfPositionTypeDTO

import Vapor

public enum HalfPositionTypeDTO: String, Codable {
    case around0 = "around0"
    case around45 = "around45"
    case around90 = "around90"
    case around135 = "around135"
    case around180 = "around180"
}