//
// MotionTypeDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.MotionTypeDTO

import Vapor

public enum MotionTypeDTO: String, Codable {
    case runningmotion1 = "runningMotion1"
    case runningmotion2 = "runningMotion2"
    case runningmotion3 = "runningMotion3"
}