//
// SportTypeDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.SportTypeDTO

import Vapor

public enum SportTypeDTO: String, Codable {
    case athletics = "athletics"
    case yoga = "yoga"
    case workout = "workout"
}