//
// UserDB.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.UserDB

import Vapor


public final class UserDB: Content {

    public var `id`: UUID?
    public var name: String
    public var email: String
    public var password: String
    public var profileImage: String
    public var token: String?
    public var chats: [UUID]

    public init(`id`: UUID?, name: String, email: String, password: String, profileImage: String, token: String?, chats: [UUID]) { 
        self.`id` = `id`
        self.name = name
        self.email = email
        self.password = password
        self.profileImage = profileImage
        self.token = token
        self.chats = chats
    }
}
