//
// UserDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.UserDTO

import Vapor


public final class UserDTO: Content {

    public var primaryId: UUID
    public var name: String
    public var email: String
    public var profileImageUrl: String?
    public var chats: [UUID]
    public var groups: [UUID]

    public init(primaryId: UUID, name: String, email: String, profileImageUrl: String?, chats: [UUID], groups: [UUID]) { 
        self.primaryId = primaryId
        self.name = name
        self.email = email
        self.profileImageUrl = profileImageUrl
        self.chats = chats
        self.groups = groups
    }
}
