//
// UserDTO.swift
//
// Generated by vapor-server-codegen
// https://github.com/thecheatah/SwiftVapor-swagger-codegen
// Template Input: /Models.UserDTO

import Vapor


public final class UserDTO: Content {

    public var primaryId: UUID
    public var name: String
    public var email: String
    public var profileImageUrl: String?
    public var sports: [SportTypeDTO]
    public var chats: [UUID]

    public init(primaryId: UUID, name: String, email: String, profileImageUrl: String?, sports: [SportTypeDTO], chats: [UUID]) { 
        self.primaryId = primaryId
        self.name = name
        self.email = email
        self.profileImageUrl = profileImageUrl
        self.sports = sports
        self.chats = chats
    }
}
