name: Building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Specify default branch
        run: git config --global init.defaultBranch main
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.0.app/Contents/Developer'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build application
        run: swift build
      - name: Test application
        run: swift test