name: Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse project
      run: sudo xcode-select -s '/Applications/Xcode_14.0.app/Contents/Developer'
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build application
        run: swift build
      - name: Test application
        run: swift test